version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - ./../mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE: ddmenv
            - MYSQL_USER: root
            - MYSQL_PASSWORD: ash1201033m
            - MYSQL_ROOT_PASSWORD: ash1201033m
        ports:
            - 3306:3306    
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/src/code
            - ../uploads:/src/uploads
        ports:
            - "8000:8000"
        depends_on:
            - db            
              